// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6lOa94--Lyqb8sbcVJPJYAdAdeAZaXU',
    appId: '1:1081382433038:web:627c997362df4a73a5675f',
    messagingSenderId: '1081382433038',
    projectId: 'mateme-e68a6',
    authDomain: 'mateme-e68a6.firebaseapp.com',
    storageBucket: 'mateme-e68a6.firebasestorage.app',
    measurementId: 'G-16CNX7C34Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsOkUqm8nBQmZjSiERtgHe2kEayJ_PsZ4',
    appId: '1:1081382433038:android:2a7f90b0a15ebe7aa5675f',
    messagingSenderId: '1081382433038',
    projectId: 'mateme-e68a6',
    storageBucket: 'mateme-e68a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUA-jOqqDKnsOTNSYAW4sIJvCEmIB2-Zo',
    appId: '1:1081382433038:ios:2a0d63b837d6fc74a5675f',
    messagingSenderId: '1081382433038',
    projectId: 'mateme-e68a6',
    storageBucket: 'mateme-e68a6.firebasestorage.app',
    iosBundleId: 'com.maksimgerbrant.datingApp2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUA-jOqqDKnsOTNSYAW4sIJvCEmIB2-Zo',
    appId: '1:1081382433038:ios:7ca07b2dddd73a5aa5675f',
    messagingSenderId: '1081382433038',
    projectId: 'mateme-e68a6',
    storageBucket: 'mateme-e68a6.firebasestorage.app',
    iosBundleId: 'com.datingapp.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl6lOa94--Lyqb8sbcVJPJYAdAdeAZaXU',
    appId: '1:1081382433038:web:9f8364b4bb33668fa5675f',
    messagingSenderId: '1081382433038',
    projectId: 'mateme-e68a6',
    authDomain: 'mateme-e68a6.firebaseapp.com',
    storageBucket: 'mateme-e68a6.firebasestorage.app',
    measurementId: 'G-WJ91X8GKT4',
  );
}
